FROM maven:3.8.5-openjdk-17 AS build

WORKDIR /app

COPY igrp-user-management/pom.xml .

RUN mvn dependency:go-offline -B

COPY igrp-user-management/src ./src

RUN mvn package -DskipTests

FROM openjdk:17-jdk-slim

RUN mkdir /config

COPY --from=build /app/target/*.jar /app/app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]

