# Use an official Maven image with JDK 21 to build the application
FROM eclipse-temurin:21-jdk-alpine AS build

# Define build-time argument
ARG SERVICE_NAME

# Set the working directory
ENV APP_HOME /app
ENV SPRING_PROFILES_ACTIVE=docker

# Copy the pom.xml and install dependencies
COPY .mvn $APP_HOME/.mvn
COPY src $APP_HOME/src
COPY mvnw $APP_HOME/mvnw
COPY mvnw.cmd $APP_HOME/mvnw.cmd
COPY pom.xml $APP_HOME/pom.xml

WORKDIR $APP_HOME

# Package the application
RUN chmod +x $APP_HOME/mvnw
RUN ./mvnw package -DskipTests

# Runtime image
FROM eclipse-temurin:21-jdk-alpine

# Define runtime environment variable
ENV SERVICE_NAME=${SERVICE_NAME}
ENV SPRING_PROFILES_ACTIVE=docker

# Set the working directory
WORKDIR /app

COPY --from=build /app/target/{{baseConfig.artifact}}-0.0.1-SNAPSHOT.jar ./

# Expose the port that the application will run on
EXPOSE 8080

# Command to run the application
CMD ["sh", "-c", "java -jar ./{{baseConfig.artifact}}-0.0.1-SNAPSHOT.jar"]